### ISSUE TITLE
Is it going to replace PyNGL?

### ISSUE THREAD

**Issue by melodyjulia** [NCAR/GeoCAT-examples#180]
PyNGL has almost all GeoCAT-examples. If one use matplotlib/cartopy and etc, why to mimic the style of NCL/PyNGL? What's the advantages of GeoCAT-examples over PyNGL?  e.g. GeoCAT-examples usually begin with a dozen of "import" before any meaningful things, it looks lumpish.

**Comment by clyne** [comment]
That is a great question. Thank you for asking. There are a number of reasons that the GeoCAT team has been exploring using MatPlotLib, Cartopy, and other Python ecosystem packages as an alternative to PyNGL. In no particular order some of the most important reasons are:

1. PyNGL is built on top of code that is now decades old. The developers have long since retired or departed, and we no longer have the expertise needed to maintain and enhance the underpinnings of PyNGL.
2. Unlike PyNGL, MatPlotLib, etc. have enormous user bases, and these package are actively being developed by large communities of developers. It makes no sense for us to reinvent the wheel.
3. Early career scientists have very likely been exposed to MatPlotLib, etc. throughout their academics. The same cannot be said for PyNGL.
4. We simply do not have the staff resources to develop PyNGL further, particularly given that  excellent alternatives exist. Even if cost were no object it is very difficult to hire and retain software engineers that have the skillset for, or interest in, maintaining legacy code that will do very little to help them develop marketable skills for the future.

Regarding the import statements that precede many examples: these could easily be captured in a single file and imported with a single line of code. Perhaps that is something the GeoCAT team will explore

Thank you again for your question and interest.

**Comment by melodyjulia** [comment]
Thanks for your kindly reply. Maintaining and enhancing the legacy code do need lots of efforts and resources. 

As for the age-old underpinnings of PyNGL, if it might be possible to adapt PyNGL on top of Matplotlib and Cartopy but without exposing details of Matplotlib and Cartopy to users. In this way, NCL/PyNGL users can still best use their knowledge on NCL/PyNGL's workflow and resources and make a quick transition. It will benefit a large community.

**Comment by clyne** [comment]
We did consider migrating PyNGL to a more modern backend, but ultimately concluded that the effort was not the best use of our limited staff resources. The GeoCAT-examples gallery effort started as a small experiment with a two-day hackathon to see what was possible, and blossomed into a much large effort once we learned how capable Matplotlib and Cartopy actually were. Most of the work on the gallery has been done by students and other volunteers who are interested in advancing their Python and MPL skills. Because each example plot is small in scope, and largely independent from other plots, the gallery work is very well suited for outside contributors. Refactoring PyNGL, on the other hand, would require a more experienced engineering team, more planning, etc.

Thanks again for your comments and interest in the project. These are important questions to ask.

**Comment by erogluorhan** [comment]
Hi @melodyjulia 

In addition to the conversation you and @clyne had previously here, I'd like to let you know the latest community update of the GeoCAT team including PyNGL and other NCL related toolkits: [November 2020 Update](https://geocat.ucar.edu/blog/2020/11/11/November-2020-update)

Please let us know if we can be of further support.

Regards.

Orhan - GeoCAT

**Comment by melodyjulia** [comment]
Thanks for your tremendous work on GeoCAT, NCL, PyNGL and etc.

I have read [November 2020 Update](https://geocat.ucar.edu/blog/2020/11/11/November-2020-update), it's very helpful on clarifying current status of GeoCAT, NCL, PyNGL and future plan on them.

It would be nice to see GeoCAT can provide a consistent experience on plotting.

**Comment by erogluorhan** [comment]
@melodyjulia 

Thank you very much!

I am closing this issue, though, we need community feedbacks much on our growing efforts, so please let us know any inconsistencies/requests as Github Issues through our repositories.

Regards.

Orhan - GeoCAT
