### ISSUE TITLE
Yapf github action tweaks

### ISSUE THREAD

**Issue by anissa111** [NCAR/GeoCAT-examples#231]
Reasons for tweaking:
- Repeated formatting pushes could be consolidated into one automated action at a later stage of development instead of every push
- Pulling in files not specifically edited in branch/PR
- Clogging of commit messages
- Workflow simplification

Suggested changes:
- Action triggered on PR creation or merge action
- yapf formatting based on a diff from head to format only relevant files, like:
`run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)`

**Comment by erogluorhan** [comment]
I agree with all of these comments; especially with "clogging of commit lists" due to one auto-formatter commit per one regular commit, as well as "Pulling in files not specifically edited in branch".

@pilotchute could you please investigate how to address these needs, either adjusting the current workflow or switching to precommit webhook for each repo we applied this current workflow?

**Comment by erogluorhan** [comment]
@michaelavs Please feel free to share your thoughts, if any, here with the current auto-formatter workflow.

**Comment by michaelavs** [comment]
I think this would be a good update! It would definitely be useful to circumvent reformatting files every time they are pushed and instead only once or twice during the major events (creation and/or merge).

**Comment by pilotchute** [comment]
There is a solution that will work for this already implemented on geocat-f2py, I'll implement it here soon.
