### ISSUE TITLE
mac-os tests bottleneck

### ISSUE THREAD

**Issue by anissa111** [NCAR/GeoCAT-examples#473]
Should we consider reducing the number of tests that run on mac-os? We have 4 mac-os runs per run and a concurrency limit of 5. 

I am unclear about the purpose of testing all the versions on mac-os as well as ubuntu, as the differences between the two versions would likely be cosmetic rather than errors, which GitHub Actions do not account for. Is there any scenario where mac-os would outright fail where ubuntu would not?

**Comment by anissa111** [comment]
@hCraker @erogluorhan @michaelavs

**Comment by erogluorhan** [comment]
I'd say testing for both macos and ubuntu is important because in the dependency list, we have platform-specifically built tools such as geocat-comp and WRF-Python and likely a few others. They have different builds for different platforms, and there is a chance that at some point we'd have errors in a platform but not on the other. 

Regarding the concurrency limit, 5 is too low :) Anyways, if that's really an issue, we'd think of testing macos only for the lowest and highest supported Python versions for push/pull-requests but creating a new workflow to test macos only for all the versions (what we currently do) to be run nightly on the main branch only (this would mean splitting the current `ci.yml` to seperate the cron-job from the others and to specify branch name.

**Comment by anissa111** [comment]
> I'd say testing for both macos and ubuntu is important because in the dependency list, we have platform-specifically built tools such as geocat-comp and WRF-Python and likely a few others. They have different builds for different platforms, and there is a chance that at some point we'd have errors in a platform but not on the other.

Ahh, makes sense!

> Regarding the concurrency limit, 5 is too low :) Anyways, if that's really an issue, we'd think of testing macos only for the lowest and highest supported Python versions for push/pull-requests but creating a new workflow to test macos only for all the versions (what we currently do) to be run nightly on the main branch only (this would mean splitting the current `ci.yml` to separate the cron-job from the others and to specify branch name.

Yeah, that's essentially what I was thinking. 

Normally it probably won't matter that much, but occasionally there will be times (like tomorrow) where I anticipate multiple PRs being approved/merged/updated in a fairly short timespan where the concurrency limit will really get us.
