### ISSUE TITLE
Website Link 404 not found.

### ISSUE THREAD

**Issue by jrbuzan** [NCAR/geocat-examples#554]
Hello GeoCat Developers:

The link to from installation page to the detailed installation description is 404 not found. This is problematic as I would like to install GeoCat.

Installation page
https://geocat-examples.readthedocs.io/en/latest/install.html

404 not found.
https://geocat-examples.readthedocs.io/en/latest/(https:/geocat.ucar.edu/pages/contributing.html)

Best regards,
-Jonathan R. Buzan

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**OS:**
 [e.g. iOS]

**Environment**
Paste the output from ```conda list``` here

**Comment by kafitzgerald** [comment]
Thanks for reporting the broken link to that contributing page!  

We're in the process of fixing this, but it's gotten wrapped up in some other infra related issues.  Another nudge is helpful though.

In the meantime, you can find the content you're looking for in the [GeoCAT-viz](https://geocat-viz.readthedocs.io/en/latest/installation.html) and [GeoCAT-comp](https://geocat-comp.readthedocs.io/en/stable/installation.html) installation documentation.  

A quick question though (since I think the statement surrounding the broken link might be somewhat misleading and I'd love to check that assumption)... are you looking to set up a Python environment where you can run these examples scripts (including geoCAT-viz / geoCAT-comp) or just install the geoCAT-viz and/or comp packages so you can use functionality from those?  If you're looking to do the former, [this section of the geoCAT-examples installation documentation](https://geocat-examples.readthedocs.io/en/latest/install.html#creating-a-conda-environment) should get you all set up.  If you're looking to do the latter, the links above to the GeoCAT-viz and GeoCAT-comp documentation is where you'll want to look.

**Comment by kafitzgerald** [comment]
Should be updated now for clarity and have the broken link removed.  

Let us know if you run into any other problems!
